package com.cs.tmt.service.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-03T19:42:39.949+05:30
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://api.service.tmt.cs.com/", name = "InfoDataService")
@XmlSeeAlso({ObjectFactory.class})
public interface InfoDataService {

    @WebMethod
    @RequestWrapper(localName = "getInfoDataDetails", targetNamespace = "http://api.service.tmt.cs.com/", className = "com.cs.tmt.service.api.GetInfoDataDetails")
    @ResponseWrapper(localName = "getInfoDataDetailsResponse", targetNamespace = "http://api.service.tmt.cs.com/", className = "com.cs.tmt.service.api.GetInfoDataDetailsResponse")
    public void getInfoDataDetails(
        @WebParam(mode = WebParam.Mode.INOUT, name = "root", targetNamespace = "")
        javax.xml.ws.Holder<InfoData> root
    );

    @WebMethod
    @RequestWrapper(localName = "getInfoDataVersion", targetNamespace = "http://api.service.tmt.cs.com/", className = "com.cs.tmt.service.api.GetInfoDataVersion")
    @ResponseWrapper(localName = "getInfoDataVersionResponse", targetNamespace = "http://api.service.tmt.cs.com/", className = "com.cs.tmt.service.api.GetInfoDataVersionResponse")
    @WebResult(name = "root", targetNamespace = "")
    public com.cs.tmt.service.api.InfoData getInfoDataVersion();
}
